### ISSUE TITLE
Removing <Press enter to continue>

### ISSUE THREAD

**Issue by bryan-brancotte** [cyclone-project/cyclone-python-pam#10]
Having to type enter a second time after having typed the ssh command is a little bit annoying. Is it possible to not have to type enter ?
I tried to remove this line, but then "Browse to http://ip:port to login" is not displayed.

**Comment by Sturgelose** [comment]
This is part of how the PAM system works: If you want to print to screen, then you need at least the user to interact with you. 

I also tried the same, and the main problem is that until you don't press <enter> the thread in the python code is frozen (eve if you execute a multi threaded program). This I think is because of security.

If otherwise, you don't set the <enter>, then the URL is not displayed. I've been debugging it down to the source code and I haven't been able to find any solution. So this is why I left the <enter> part there

**Comment by bryan-brancotte** [comment]
Ok, too bad, thanks.
